correct indirection for supported mode + add snr typedef
ietf-ccamp-wg/ietf-ccamp-layer0-types-ext pull request #11
Opened 2021-01-29 16:01 UTC by EstherLerouzic

- there is a level missing for the reference to supported-modes/mode-id
- the optical topology references  snr ("type l0-types-ext:snr;"),
  but the type was not defined yet

Signed-off-by: EstherLerouzic <esther.lerouzic@orange.com>

2021-02-03 11:00 UTC, sergiobelotti approved these changes

2021-02-04 10:34 UTC, italobusi requested changes
The proposed fixes are needed but requires some changes: please see detailed comments

Co-authored-by: sergiobelotti sergio.belotti@nokia.com

2021-02-04 10:34 UTC, italobusi commented on ietf-layer0-types-ext.yang
> +                  must "../../../../supported-mode[mode-id=current()]/"
This is correct but please check that we do not exceed the 69 line width:

```suggestion
                  must "../../../../"
                     + "supported-mode[mode-id=current()]/"
```

Co-authored-by: sergiobelotti sergio.belotti@nokia.com

2021-02-04 10:34 UTC, italobusi commented on ietf-layer0-types-ext.yang
>                       + "operational-mode" {
It seems that also this must statement is not correct

```suggestion
                  must "../../../../"
                     + "supported-mode[mode-id=current()]/"
                     + "organizational-mode" {
```

Co-authored-by: sergiobelotti <sergio.belotti@nokia.com>

2021-02-04 10:34 UTC, italobusi commented on ietf-layer0-types-ext.yang
> +  }
Please check and propose an alignment with the previous definition which is used by https://tools.ietf.org/html/draft-ietf-ccamp-optical-impairment-topology-yang-05 but was committed to the transponder-model-types branch and not to the master branch and that we have just merged with PR#13

```
  typedef snr {
    type decimal64 {
      fraction-digits 2;
    }
    units "dB@0.1nm";
    description
      "(Optical) Signal to Noise Ratio measured over 0.1 nm
       resolution bandwidth";
  }

```

Co-authored-by: sergiobelotti sergio.belotti@nokia.com

2021-02-09 09:03 UTC, italobusi commented on ietf-layer0-types-ext.yang
> +                  must "../../../../supported-mode[mode-id=current()]/"
Addressed with https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/11/commits/9e2c4758a623ed7879d84d055d58807d3df2bc51

2021-02-09 09:04 UTC, italobusi commented on ietf-layer0-types-ext.yang
>                       + "operational-mode" {
Addressed with https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/11/commits/9e2c4758a623ed7879d84d055d58807d3df2bc51

2021-02-09 09:04 UTC, italobusi commented on ietf-layer0-types-ext.yang
> +  }
Addressed with https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/11/commits/9e2c4758a623ed7879d84d055d58807d3df2bc51

2021-02-09 09:05 UTC, italobusi commented on ietf-layer0-types-ext.yang
> +  }
Addressed with https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/11/commits/9e2c4758a623ed7879d84d055d58807d3df2bc51

2021-02-09 09:06 UTC, italobusi approved these changes

2021-02-09 09:10 UTC, merged